name: Build Windows Release

on:
  workflow_dispatch: {}
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build EXE with PyInstaller
        shell: pwsh
        run: |
          pyinstaller --noconfirm --windowed --name PhotoWatermark --collect-all PySide6 app.py

      - name: Package artifact (zip)
        shell: pwsh
        run: |
          Compress-Archive -Path "dist/PhotoWatermark/*" -DestinationPath "PhotoWatermark-win64.zip"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PhotoWatermark-win64
          path: PhotoWatermark-win64.zip

      - name: Create GitHub Release (if tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: PhotoWatermark-win64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
